var PC=PC||{};if(typeof Object.create!=="function")Object.create=function(a,b){function c(){}if(typeof a!=="object")throw new TypeError;c.prototype=a;var d=new c;if(a)d.constructor=c;if(arguments.length>1){if(b!==Object(b))throw new TypeError;Object.defineProperties(d,b)}return d};
(function(){var a;if(!(a=!Object.defineProperty)){var b;try{Object.defineProperty({},"x",{}),b=!0}catch(c){b=!1}a=!b}if(a){var d=Object.defineProperty;Object.defineProperty=function(a,b,c){if(d)try{return d(a,b,c)}catch(h){}if(a!==Object(a))throw new TypeError("Object.defineProperty called on non-object");Object.prototype.__defineGetter__&&"get"in c&&Object.prototype.__defineGetter__.call(a,b,c.get);Object.prototype.__defineSetter__&&"set"in c&&Object.prototype.__defineSetter__.call(a,b,c.set);if("value"in
c)a[b]=c.value;return a}}})();if(typeof Object.defineProperties!=="function")Object.defineProperties=function(a,b){if(a!==Object(a))throw new TypeError("Object.defineProperties called on non-object");for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&Object.defineProperty(a,c,b[c]);return a};
if(!Array.prototype.forEach)Array.prototype.forEach=function(a,b){if(this===void 0||this===null)throw new TypeError;var c=Object(this),d=c.length>>>0;if(typeof a!=="function")throw new TypeError;var e;for(e=0;e<d;e++)e in c&&a.call(b,c[e],e,c)};
function warningRequest(a,b,c,d){c=c||void 0;d=d===!1?!1:!0;var e=XMLHttpObject(),f,g={Accept:"text/javascript, text/html, application/xml, text/xml, */*"};if(e){e.open("GET",a,d);for(f in g)e.setRequestHeader(f,g[f]);setWarningHeader(e,b);if(d)e.onreadystatechange=function(){if(e.readyState==4&&!(e.status!=200&&e.status!=304)&&e.readyState==4&&c)return c(e)};e.send(null);if(!d&&c)return c(e)}}
function request(a,b,c,d){b=b||{};a=url(a,b);c=c||void 0;d=d===!1?!1:!0;var e=XMLHttpObject(),f;b={Accept:"text/javascript, text/html, application/xml, text/xml, */*"};if(e){e.open("GET",a,d);for(f in b)e.setRequestHeader(f,b[f]);if(d)e.onreadystatechange=function(){if(e.readyState==4&&!(e.status!=200&&e.status!=304)&&e.readyState==4&&c)return c(e)};e.send(null);if(!d&&c)return c(e)}}
function setWarningHeader(a,b){typeof XMLHttpRequest!=="undefined"&&(!b&&document.all&&!document.querySelector?a.setRequestHeader("Warning"):a.setRequestHeader("Warning",b))}
function ajax(a,b,c){b=b||{};c=c||{};c.success=c.success||void 0;c.asynchronous=c.asynchronous===!1?!1:!0;c.method=c.method||"GET";a=c.method=="POST"?a:url(a,b);b=c.method=="POST"&&b?httpBuildQuery(b):null;var d=XMLHttpObject(),e,f={Accept:"text/javascript, text/html, application/xml, text/xml, */*"};if(d){d.open(c.method,a,c.asynchronous);for(e in f)d.setRequestHeader(e,f[e]);c.method=="POST"&&d.setRequestHeader("Content-type","application/x-www-form-urlencoded");if(c.asynchronous)d.onreadystatechange=
function(){if(d.readyState==4&&!(d.status!=200&&d.status!=304)&&d.readyState==4&&c.success)return c.success(d)};d.send(b);if(!c.asynchronous&&c.success)return c.success(d)}}function XMLHttpObject(){for(var a=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}],b=!1,c=0;c<a.length;c++){try{b=a[c]()}catch(d){continue}break}return b}
function getFromStr(a,b){if(typeof b==="string"){var c=a+"=",d=b.split(/[;&]/),e,f;for(e=0;e<d.length;e++){for(f=d[e];f.charAt(0)===" ";)f=f.substring(1,f.length);if(f.indexOf(c)===0)return f.substring(c.length,f.length)}}}function newImage(a){var b=new Image;b.style.visibility="hidden";b.style.position="absolute";b.src=a}function url(a,b){b=b||{};a+=a.indexOf("?")?"?":"&";a+=httpBuildQuery(b);return a}
function httpBuildQuery(a){var b="",c=0,d;for(d in a)a.hasOwnProperty(d)&&(b+=c>0?"&":"",b+=d+"="+urlencode(a[d]),c++);return b}function urlencode(a){a=(a+"").toString();return encodeURIComponent(a).replace(/!/g,"%21").replace(/'/g,"%27").replace(/\(/g,"%28").replace(/\)/g,"%29").replace(/\*/g,"%2A").replace(/%20/g,"+")}
function lzwEncode(a){var b={};a=(a+"").split("");var c=[],d,e=a[0],f=256,g;if(e){for(g=1;g<a.length;g++)d=a[g],typeof b[e+d]=="undefined"||!b[e+d]?(c.push(e.length>1?b[e]:e.charCodeAt(0)),b[e+d]=f,f++,e=d):e+=d;c.push(e.length>1?b[e]:e.charCodeAt(0));for(g=0;g<c.length;g++)c[g]=String.fromCharCode(c[g])}return c.join("")}
function lzwDecode(a){var b={};a=(a+"").split("");var c=a[0],d=c,e=[c],f=256,g,h;for(h=1;h<a.length;h++)g=a[h].charCodeAt(0),g=g<256?a[h]:b[g]?b[g]:d+c,e.push(g),c=g.charAt(0),b[f]=d+c,f++,d=g;return e.join("")}function encodeUTF8(a){return unescape(encodeURIComponent(a))}function decodeUTF8(a){return decodeURIComponent(escape(a))}
(function(a){var b=a.Base64,c=function(a){for(var b={},c=0,d=a.length;c<d;c++)b[a.charAt(c)]=c;return b}("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"),d=String.fromCharCode,e=function(a){var b;return a.length<2?(b=a.charCodeAt(0),b<128?a:b<2048?d(192|b>>>6)+d(128|b&63):d(224|b>>>12&15)+d(128|b>>>6&63)+d(128|b&63)):(b=65536+(a.charCodeAt(0)-55296)*1024+(a.charCodeAt(1)-56320),d(240|b>>>18&7)+d(128|b>>>12&63)+d(128|b>>>6&63)+d(128|b&63))},f=/[\uD800-\uDBFF][\uDC00-\uDFFFF]|[^\x00-\x7F]/g,
g=function(a){return a.replace(f,e)},h=function(a){var b=[0,2,1][a.length%3];a=a.charCodeAt(0)<<16|(a.length>1?a.charCodeAt(1):0)<<8|(a.length>2?a.charCodeAt(2):0);return["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>18),"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>12&63),b>=2?"=":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>6&63),b>=1?"=":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a&
63)].join("")},j=a.btoa?function(b){return a.btoa(b)}:function(a){return a.replace(/[\s\S]{1,3}/g,h)},i=function(a,b){return!b?j(g(a)):j(g(a)).replace(/[+\/]/g,function(a){return a=="+"?"-":"_"}).replace(/=/g,"")},o=RegExp("[\u00c0-\u00df][\u0080-\u00bf]|[\u00e0-\u00ef][\u0080-\u00bf]{2}|[\u00f0-\u00f7][\u0080-\u00bf]{3}","g"),p=function(a){switch(a.length){case 4:return a=((7&a.charCodeAt(0))<<18|(63&a.charCodeAt(1))<<12|(63&a.charCodeAt(2))<<6|63&a.charCodeAt(3))-65536,d((a>>>10)+55296)+d((a&1023)+
56320);case 3:return d((15&a.charCodeAt(0))<<12|(63&a.charCodeAt(1))<<6|63&a.charCodeAt(2));default:return d((31&a.charCodeAt(0))<<6|63&a.charCodeAt(1))}},m=function(a){return a.replace(o,p)},q=function(a){var b=a.length,e=b%4;a=(b>0?c[a.charAt(0)]<<18:0)|(b>1?c[a.charAt(1)]<<12:0)|(b>2?c[a.charAt(2)]<<6:0)|(b>3?c[a.charAt(3)]:0);a=[d(a>>>16),d(a>>>8&255),d(a&255)];a.length-=[0,0,2,1][e];return a.join("")},n=a.atob?function(b){return a.atob(b)}:function(a){return a.replace(/[\s\S]{1,4}/g,q)},r=function(a){return m(n(a))},
k=function(a){return r(a.replace(/[-_]/g,function(a){return a=="-"?"+":"/"}).replace(/[^A-Za-z0-9\+\/]/g,""))};a.Base64={VERSION:"2.1.2",atob:n,btoa:j,fromBase64:k,toBase64:i,utob:g,encode:i,encodeURI:function(a){return i(a,!0)},btou:m,decode:k,noConflict:function(){window.Base64=a.Base64;a.Base64=b;return window.Base64}};if(typeof Object.defineProperty==="function"){var l=function(a){return{value:a,enumerable:!1,writable:!0,configurable:!0}};a.Base64.extendString=function(){Object.defineProperty(String.prototype,
"fromBase64",l(function(){return k(this)}));Object.defineProperty(String.prototype,"toBase64",l(function(a){return i(this,a)}));Object.defineProperty(String.prototype,"toBase64URI",l(function(){return i(this,!0)}))}}})(this);PC.PersistentStorage=function(){this.name="PC.PersistentStorage";this.highCapacity=this.remoteAccess=!1;this.baseURL="";this.key="ecdst"};PC.PersistentStorage.prototype.constructor=PC.PersistentStorage;PC.PersistentStorage.prototype.get=function(){};
PC.PersistentStorage.prototype.set=function(){};PC.Cookie=function(){PC.PersistentStorage.call(this);this.name="PC.Cookie";this.remoteAccess=!1;this.highCapacity=!0;this.URL="//asset.easydmp.net/cookie.php";this.number=1;this.maxSize=4};PC.Cookie.prototype=Object.create(PC.PersistentStorage.prototype);PC.Cookie.prototype.get=function(){var a="",b;for(b=1;b<=this.number;b++)a+=getFromStr(this.key+b,window.document.cookie);return a};
PC.Cookie.prototype.set=function(a){if(PC.Cookie.authorized()){a=PC.Cookie.splitSlice(a,4*Math.pow(10,3)-10);var b,c;this.expire();this.number=a.length;b=new Date;b.setTime(b.getTime()+11232E5);for(var d="expires="+b.toUTCString(),e=0;e<a.length;e++)c=a[e],b=e+1,window.document.cookie=this.key+b+"="+c+"; "+d+"; domain=.easydmp.net; path=/"}else request(this.URL,{data:a},null,!0);return this};PC.Cookie.prototype.expire=function(){for(var a=1;a<=this.number;a++)window.document.cookie=this.key+a+"=; expires=Mon, 20 Sep 2010 00:00:00 UTC; path=/"};
PC.Cookie.splitSlice=function(a,b){for(var c=Math.ceil(a.length/b),d=Array(c),e=0;e<c;e++)d[e]=a.substring(e*b,e*b+b);return d};PC.Cookie.authorized=function(){var a=!1,b=new Date;b.setTime(b.getTime()+11232E5);b="expires="+b.toUTCString();window.document.cookie="test=test; "+b+"; domain=.easydmp.net; path=/";getFromStr("test",window.document.cookie)=="test"&&(a=!0);return a};
PC.ETag=function(){PC.PersistentStorage.call(this);this.name="PC.ETag";this.remoteAccess=!0;this.highCapacity=!1;this.eTagURL="//asset.easydmp.net/etag.php";this.eTagData=void 0};PC.ETag.prototype=Object.create(PC.PersistentStorage.prototype);PC.ETag.prototype.get=function(){return warningRequest(this.baseURL+this.eTagURL,"",function(a){return a.getResponseHeader("Etag")},!0)};PC.ETag.prototype.set=function(a){a&&warningRequest(this.baseURL+this.eTagURL,a,null,!0);return this};
PC.GlobalStorage=function(){PC.PersistentStorage.call(this);this.name="PC.GlobalStorage";this.remoteAccess=!1;this.highCapacity=!0;this.host=function(){return window.location.host.replace(/:\d+/,"")}};PC.GlobalStorage.prototype=Object.create(PC.PersistentStorage.prototype);PC.GlobalStorage.prototype.get=function(){try{if(window.globalStorage)return window.globalStorage[this.host][this.key]}catch(a){}};
PC.GlobalStorage.prototype.set=function(a){try{window.globalStorage&&(window.globalStorage[this.host][this.key]=a)}catch(b){}return this};PC.LocalStorage=function(){PC.PersistentStorage.call(this);this.name="PC.LocalStorage";this.remoteAccess=!1;this.highCapacity=!0};PC.LocalStorage.prototype=Object.create(PC.PersistentStorage.prototype);PC.LocalStorage.prototype.get=function(){try{if(window.localStorage)return window.localStorage.getItem(this.key)}catch(a){}};
PC.LocalStorage.prototype.set=function(a){try{window.localStorage&&window.localStorage.setItem(this.key,a)}catch(b){}return this};PC.PersistentStorageManager=function(a){this.storages=a||[new PC.LocalStorage,new PC.GlobalStorage,new PC.Cookie,new PC.ETag];this.value=this.key=void 0;this.separator=":"};PC.EventEmitter=PC.EventEmitter||void 0;PC.PersistentStorageManager.prototype=typeof PC.EventEmitter!="undefined"?Object.create(PC.EventEmitter.prototype):{};
PC.PersistentStorageManager.prototype.init=function(){this.synchronize()};PC.PersistentStorageManager.prototype.get=function(){for(var a,b=0;b<this.storages.length;b++)if(a=this.storages[b].get(),a!="undefined"&&a!=null)return PC.PersistentStorageManager.Decode(a)};PC.PersistentStorageManager.prototype.getKey=function(){return this.key};PC.PersistentStorageManager.prototype.getValue=function(){return this.value};
PC.PersistentStorageManager.prototype.set=function(a,b){a=a||"";if(b===void 0){var c=a.split(/:(.+)?/,2);a=c[0];b=c[1]}b=b||"";c={};var d;this.key=a;this.value=b;for(var e=0;e<this.storages.length;e++)c=this.storages[e],c.highCapacity===!0?(d=b?PC.PersistentStorageManager.Encode(a+this.separator+b):PC.PersistentStorageManager.Encode(a),c.set(d)):(a=a?PC.PersistentStorageManager.Encode(a):a,c.set(a));return this};
PC.PersistentStorageManager.prototype.synchronize=function(){var a=this.get();a?a.indexOf(this.separator)!=-1?(a=/^([^:]*):(.*)/.exec(a),typeof PC.EventEmitter!="undefined"&&this.emit("data",a[2]),this.set(a[1],a[2])):(typeof PC.EventEmitter!="undefined"&&this.emit("noData"),this.set(a)):typeof PC.EventEmitter!="undefined"&&this.emit("noData");return this};PC.PersistentStorageManager.Encode=function(a){return a?window.Base64.encode(encodeUTF8(lzwEncode(a))):a};
PC.PersistentStorageManager.Decode=function(a){return a?lzwDecode(decodeUTF8(window.Base64.decode(a))):a};var psm=new PC.PersistentStorageManager;function pixel(a){var b=document.createElement("img");b.src=a;b.style.position="absolute";b.style.height=1;b.style.width=1;try{document.body.insertBefore(b,document.body.firstChild)}catch(c){}}function new_iframe(a){var b=document.createElement("IFRAME");b.setAttribute("src",a);b.style.width="0px";b.style.height="0px";document.body.appendChild(b)}
var successfullyGetData=function(a){a=window.JSON.parse(a.responseText);a.update=1;for(var b in a.dl)if(a.dl.hasOwnProperty(b)){var c=0;if(a.last_site_id)c=a.last_site_id;pixel(document.location.protocol+"//p-eu.acxiom-online.com/pixel/ema?eml="+a.dl[b]+"&ha=md5&pid=1053&t=105301&sc="+c+"&ot=pixel")}if(document.location.protocol!="https:")for(b in a.dl_ad)a.dl_ad.hasOwnProperty(b)&&pixel(document.location.protocol+"//ext.adleadevent.com/adtckrtg.php?ids=1249&hash="+a.dl_ad[b]);if(a.last_site_id)for(b in a.dl_em)a.dl_em.hasOwnProperty(b)&&
pixel(document.location.protocol+"//asset.email-match.com/"+a.last_site_id+"/asset?noedmpr=1&type=IMG&email="+a.dl_em[b]+"@md5");else for(b in a.dl_em)a.dl_em.hasOwnProperty(b)&&pixel(document.location.protocol+"//asset.email-match.com/791/asset?noedmpr=1&type=IMG&email="+a.dl_em[b]+"@md5");for(b in a.dl_eff)a.dl_eff.hasOwnProperty(b)&&pixel(document.location.protocol+"//asset.email-match.com/1033/asset?noedmpr=1&type=IMG&email="+a.dl_eff[b]+"@md5");for(b in a.dl_lbd)a.dl_lbd.hasOwnProperty(b)&&pixel(document.location.protocol+
"//mt.mediapostcommunication.net/51?md5="+a.dl_lbd[b]+"&_cid=ematch");for(b in a.dl_lp)a.dl_lp.hasOwnProperty(b)&&new_iframe(document.location.protocol+"//cookies.leadplace.fr/wckr.php?id=SQU1&id3rd="+a.dl_lp[b]);for(b in a.dl_adlp)a.dl_adlp.hasOwnProperty(b)&&new_iframe(document.location.protocol+"//hubtr.mindlytix.com/adlp/ema/cm/?sid="+a.dl_adlp[b]);b=a.last_site_id||"";c=document.createElement("iframe");c.src=document.location.protocol+"//asset.easydmp.net/script_graphinium.php?lastsiteid="+b+
"&data="+a.dl_gm.join()+"&mc="+a.dl_gm_mc.join();c.style.display="none";c.style.visibility="hidden";c.style.opacity="0";c.style.width="0px";c.style.height="0px";c.style.position="absolute";document.body.insertBefore(c,document.body.firstChild)};ajax(document.location.protocol+"//asset.easydmp.net/get_delivery_data.php",{data:psm.get()},{method:"POST",asynchronous:!0,success:successfullyGetData});
