(function(c,k,n){c.execute(function(){c.when("A").register("sg-jsutil",function(b){var c=b.$;return{safeCall:function(b,h){return c.isFunction(b)?b(h):h}}});c.when("A").register("dombinder",function(b){function c(e,d){for(var h=0,d=d.split("."),b=d.length;h<b;h++)e=e&&e[d[h]];return e}function j(b){return h.map(h(b).data("bind").split(","),function(d){var d=d.split(":"),c=h.trim(d[0]),l=h.trim(d[1]),j=e[c];if(j)return j.init&&j.init(b,l),function(d){j.update(b,l,d)}})}var h=b.$,e={text:{update:function(e,
d,b){h(e).text(c(b,d)||"")}},html:{update:function(e,d,b){h(e).html(c(b,d)||"")}},href:{update:function(e,d,b){h(e).attr("href",c(b,d)||"")}},trimText:{update:function(e,d){var b=h(e),c=b.text();if(c.length>d){for(var l=d-4;l>=0&&"[.,-/#!$%^&*;:{}=-_`~()] ".indexOf(c[l])>0;)l--;b.text(c.substring(0,l>=0?l+1:d-3)+"...")}}},value:{update:function(e,d,b){h(e).val(c(b,d)||"")}},visible:{update:function(e,d,b){var j=!1;d.charAt(0)==="!"&&(j=!0,d=d.substring(1));d=!!c(b,d);j!==d?h(e).show():h(e).hide()}},
css:{init:function(e,d){var b=h(e),c=b.data("dombcss")||[];c[d]="";b.data("dombcss",c)},update:function(e,d,b){var e=h(e),j=e.data("dombcss"),t=j[d],b=c(b,d);t!==b&&(j[d]=b,t&&e.removeClass(t),b&&e.addClass(b))}},attr:{init:function(e,d){var b=h(e),c=b.data("dombattr")||[];c[d]={};b.data("dombattr",c)},update:function(e,d,b){var j=h(e),e=j.data("dombattr"),t=e[d],b=c(b,d);t!==b&&(e[d]=b,t&&h.each(t,function(d){j.removeAttr(d)}),b&&h.each(b,function(d,a){j.attr(d,a)}))}}};return{init:function(e){var d=
{$root:e,bindings:[]};e.find("[data-bind]").each(function(){h.each(j(this),function(e,b){d.bindings.push(b)})});return d},update:function(e,d){h.each(e.bindings,function(e,b){b(d)})}}});c.when("A").register("gwAjax",function(b){return function(c,j){function h(d,e,b){typeof k.ue==="object"&&(j.errorCounter?k.ue.count(j.errorCounter,(k.ue.count(j.errCounter)||0)+1):k.ue.count("gwAjaxError",(k.ue.count("gwAjaxError")||0)+1));typeof k.ueLogError&&k.ueLogError({logLevel:"WARN",attribution:"gwAjax-"+(j.id||
c),message:"gwAjax call failed "+(JSON&&JSON.stringify?JSON.stringify({url:c,"params-data":j.params||j.data}):"")});typeof i==="function"&&i(d,e,b)}var j=b.copy(j),e=j.success,i=j.error;j.success=function(d,b,c){d.error?h(d,b,c):typeof e==="function"&&e(d,b,c)};j.error=h;j.data=j.params?j.params:j.data;typeof k.ue==="object"&&k.ue.count("gwAjaxCall",(k.ue.count("gwAjaxCall")||0)+1);return b.$.ajax(c,j)}});c.when("A","sg-jsutil","dombinder").register("productdb-binding-helper",function(b,c,j){return function(b,
e){function i(d,e){j.update(a,q(e.beforeUpdate,d));d.loading||q(e.load,d)}function d(a){m();r=function(){a(t)};t.pdb_observe(r)}function m(){t&&r&&(t.pdb_unobserve(r),r=null)}var q=c.safeCall,t=null,r=null,a=j.init(e);this.setAsin=function(a,e){e=e||{};m();t=b.get(a);i(t,e);t.loading&&d(function(a){i(a,e)});return t};this.clear=function(){m();t={};j.update(a,t)}}});c.register("sg-media-builder",function(){return function(b){var c=this,j=b.src,h=[];c.build=function(){var e=h.join("_");return{src:j.replace(/\.([^.]+)$/,
"._"+e+"_.$1"),alt:b.alt}};c.autoCrop=function(){h.push("AC");return c};c.scaleX=function(e){h.push("SX"+e);return c};c.scaleY=function(e){h.push("SY"+e);return c};c.upScaleX=function(e){h.push("UX"+e);return c};c.upScaleY=function(e){h.push("UY"+e);return c};c.scaleXY=function(e,b){return c.upScaleX(e).scaleY(b)}}});c.when("A","gwAjax").register("shogunProductDB",function(b,c){function j(h){var d=[];e[h]={loading:!0,pdb_observe:function(e){d.push(e)},pdb_unobserve:function(e){d=b.$.grep(d,function(d){return d!==
e})},_trigger:function(){b.$.each(d,function(){this.call(e[h])})}};return e[h]}function h(h,d){this.ajaxUrl=h;this.experienceStr=d;this._add=function(d){d.p&&b.$.each(d.p,function(d,h){if(h.asin){var c=e[h.asin]||j(h.asin);b.$.extend(c,h,{loading:!1,error:!1});c._trigger(h)}})};this._ajax=function(e,j){var t=b.$.extend(!0,{},h,{params:{sa:JSON.stringify(e),oe:d}});k.ue_sid&&(t.url+="/"+k.ue_sid);if(k.ue_id)t.params.rrid=k.ue_id;return c(t.url,{method:t.method,params:t.params,success:j.success,error:j.error,
id:"gw-jslibs-"+j.id})};this.get=function(d){return d in e?e[d]:j(d)}}var e={};return function(e,d){return new h(e,d)}});c.when("A").register("component-feed-carousel",function(b){var c=b.$,j=function(b,e){this.init(b,e)};j.prototype={init:function(h,e){b.$("html").hasClass("a-touch")&&h.addClass("feed-carousel-touch");this.adjustMarginOnChange=!0;this.defaultCssRightMargin=null;this.minItems=e||10;this.imgClass=".product-image";this.$carousel=h;this.touch=this.$carousel.hasClass("feed-carousel-touch");
this.ajaxSource=this.$carousel.parent().hasClass("ajaxSource");this.$shelf=this.$carousel.find(".feed-carousel-shelf");this.$viewport=this.$carousel.find(".feed-carousel-viewport");this.$spinner=this.$carousel.find(".spinner");this.$left=c(".feed-carousel-control.feed-left",h);this.$right=c(".feed-carousel-control.feed-right",h);this.$buttons=c(".feed-carousel-control",h);this.$thumb=c(".feed-scrollbar-thumb",h);this.shelfLeft=-1*parseInt(this.$shelf.css("left"),10);this.calcWidth=c("html").hasClass("a-lt-ie9");
this.noOpacity=c("html").hasClass("a-lt-ie9");this.bindEvents();this.$carousel.data("Carousel",this);this.$carousel.trigger("change")},bindEvents:function(){function h(d){return b.capabilities.pointerPrefix&&c.inArray(d.originalEvent.pointerType,[2,"touch"])>-1||b.capabilities.actionMode==="touch"}var e=this,i=c("body");e.$carousel.change(function(){e.updateItems();e.updateSpinner();e.updateShelf();e.updateControls();if(e.defaultCssRightMargin===null&&e.$shelf.children("li").first())e.defaultCssRightMargin=
parseInt(e.$shelf.children("li").first().css("margin-right"),10);e.adjustMarginOnChange&&e.adjustCardMargin()});e.$left.click(function(d){d.preventDefault();e.changePage(-1)});e.$right.click(function(d){d.preventDefault();e.changePage(1)});e.bindImageLoadEvents(e.$shelf);var d;c(k).resize(function(){clearTimeout(d);d=setTimeout(function(){var d=e.getDimensions(),d=Math.max(Math.min(d.shelfLeft,d.maxLeft),0);e.moveShelf(d)},100)});e.$thumb.mousedown(function(d){var b=d.clientX;d.which===1&&(d.preventDefault(),
e.$carousel.addClass("scrolling"),i.bind("mousemove.feed-carousel",function(d){var c=e.getDimensions(),c=Math.max(Math.min(c.shelfLeft+1/c.pageRatio*(d.clientX-b),c.maxLeft),0);b=d.clientX;e.moveShelf(c)}),c(document).bind("selectstart.feed-carousel",function(){return!1}))});i.add(k).mouseup(function(){e.$carousel.removeClass("scrolling");e.$carousel.hasClass("hovering")||e.hideControls();i.unbind("mousemove.feed-carousel");c(document).unbind("selectstart.feed-carousel")});e.$carousel.hover(function(){e.$carousel.addClass("hovering");
clearTimeout(e.hoverTimer);e.hoverTimer=setTimeout(function(){e.$carousel.hasClass("hovering")&&!e.$carousel.hasClass("touching")?e.showControls():e.$carousel.removeClass("touching")},300)},function(){e.$carousel.removeClass("hovering touching");clearTimeout(e.hoverTimer);if(!e.$carousel.hasClass("scrolling"))e.hoverTimer=setTimeout(function(){e.$carousel.hasClass("hovering")||e.hideControls()},600)});e.$carousel.bind(b.action.start,function(d){if(h(d))e.$carousel.addClass("touching"),clearTimeout(e.touchTimer),
e.touchTimer=setTimeout(function(){e.$carousel.removeClass("touching")},5E3)});e.$carousel.bind(b.action.end,function(d){h(d)&&(e.$carousel.removeClass("touching"),clearTimeout(e.touchTimer),clearTimeout(e.hoverTimer))});e.$viewport.scroll(function(){e.shelfLeft=e.$viewport.scrollLeft();e.updateControls()})},bindImageLoadEvents:function(b){var e=this;c(e.imgClass,b).one("load",function(){e.$carousel.trigger("change")})},getDimensions:function(){var b=this.$shelf.width(),e=this.shelfLeft,c=this.$carousel.width();
return{pageWidth:c,shelfWidth:b,shelfLeft:e,pageRatio:c/b,leftRatio:e/b,maxLeft:b-c}},updateItems:function(){var b=this,e=b.$shelf.find(".feed-carousel-card"),i=function(d){return d.css("display")==="none"};e.each(function(d,e){var j=c(e);return!i(j)?!0:j.find(b.imgClass).filter(function(){return!this.complete}).length<=0?(j.css("display","inline-block"),!0):!1});b.$items=e.filter(function(){return!i(c(this))})},updateShelf:function(){var b=0;this.calcWidth&&(this.$shelf.children().each(function(){b+=
c(this).outerWidth(!0)}),this.$shelf.width(b));this.touch&&this.$carousel.not(".fresh-shoveler-tablet-app .feed-carousel").height(this.$shelf.outerHeight(!0))},updateSpinner:function(){this.size()<this.minItems&&this.ajaxSource?this.$spinner.show():(this.size()<this.minItems&&typeof k.ue==="object"&&k.ue.count("shovelerNotEnoughItem",(k.ue.count("shovelerNotEnoughItem")||0)+1),this.$spinner.hide())},updateControls:function(){this.updateArrows();this.updateScrollThumb()},showControls:function(b){this.$thumb.add(this.$buttons).stop(!0,
!0).fadeIn({duration:300,complete:b,queue:!1})},hideControls:function(b){var e=this.$thumb;if(!this.$carousel.hasClass("first-carousel")||this.touch)e=e.add(this.$buttons);e.stop(!0,!0).fadeOut({duration:300,complete:b,queue:!1})},appendCards:function(b){this.$shelf.append(b);this.bindImageLoadEvents(b);this.$carousel.trigger("change")},updateArrows:function(){var b=this,e=b.getDimensions();c.each([{$e:b.$left,enabled:e.shelfLeft>0},{$e:b.$right,enabled:e.shelfLeft<e.maxLeft}],function(e,d){var c=
d.$e;d.enabled?c.removeClass("feed-control-disabled"):c.addClass("feed-control-disabled");b.noOpacity&&(d.enabled?c.css("opacity","1"):c.css("opacity","0.5"))})},updateScrollThumb:function(){var b=this.getDimensions(),e=b.leftRatio*b.pageWidth;this.$thumb.width(Math.min(b.pageRatio*b.pageWidth,b.pageWidth)).each(function(){c(this).animate({left:e},0)})},changePage:function(b){var e=this.getDimensions(),c=this.alignWithItem(e.shelfLeft+b*e.pageWidth),c=Math.min(b<0?c.right:c.left,e.maxLeft);e.shelfLeft===
c?(this.bounce(this.$shelf,-30*b),this.bounce(this.$thumb,6*b)):this.moveShelf(c,400)},moveShelf:function(b,e){var c=this,e=e||0;c.shelfLeft=b;if(c.touch)c.$viewport.animate({scrollLeft:b},e,"swing",function(){c.updateArrows()});else{var d=c.getDimensions(),d=b/d.shelfWidth*d.pageWidth;c.$shelf.animate({left:-b},e,"swing",function(){c.updateArrows()});c.$thumb.animate({left:d},e,"swing",function(){c.updateScrollThumb()})}},getItems:function(){return this.$items},size:function(){return this.getItems().length},
alignWithItem:function(b){if(b<0)return{left:0,right:0};var e=this,j=e.getItems(),d=j.map(function(){var d=e.cardPosition(c(this));if(b>=d.left&&b<=d.right)return d}).get(0);return d?d:e.cardPosition(j.last())},cardPosition:function(b){var e=b.position().left,b=e+b.outerWidth(!0);return{left:e,right:b}},bounce:function(b,e){function j(e){var b={};b[d.touch?"left":"marginLeft"]=e;return b}var d=this;b.each(function(){var d=c(this);d.animate(j(e),400,"swing",function(){d.animate(j(0),100)})})},setCardMargin:function(b){this.$shelf.children("li").first()&&
this.$shelf.children("li").first().css("margin-right")!==b+"px"&&(this.$shelf.children("li").css("margin-right",b+"px"),this.updateShelf())},adjustCardMargin:function(b){b=b===n||b===null?this.defaultCssRightMargin:b;this.setCardMargin(b);var e=this.getDimensions(),e=e.maxLeft<0?Math.ceil(-e.maxLeft/this.size()):b;this.setCardMargin(e<b?b:e)}};return{createCarousel:function(h,e){c(h).each(function(c,d){var h=b.$(d);new j(h,e)})}}})})})(function(){var c=window.AmazonUIPageJS||window.P,k=c._namespace||
c.attributeErrors;return k?k("AmazonGatewayAuiAssets"):c}(),window);