(function(c){c.execute(function(){c.when("generic-observable").register("gw-herotator-controller",function(c){var n=function(){};return function(b){function l(){p.notifyObservers("delayBegin")}function j(){p.notifyObservers("delayInterrupted")}function h(a){for(var f=0;f<s.length;f++)if(s[f]===a)return f+1}function e(g){g=g||{};return{delay_complete:g.delay_complete||n,js_ready:g.js_ready||n,fg_loaded:g.fg_loaded||n,mouse_move:g.mouse_move||n,mouse_leave:g.mouse_leave||n,delay_interrupted_timeout:g.delay_interrupted_timeout||
n,rotation_complete:g.rotation_complete||n,goto_card:function(a){a!==x&&f.user_navigation(s[a-1])},user_navigation:g.user_navigation||function(g){f=new a(g)},user_interaction:g.user_interaction||function(){f.user_navigation(s[x-1])},stop_autorotation:g.stop_autorotation||function(){f.user_navigation(s[x-1])},pause:g.pause||n,resume:g.resume||n}}function i(){function a(){!b&&y[g]&&(f=A===1?new o:new q)}l();var g=s[(x-1+1)%A+1-1],b=!0;return new e({fg_loaded:function(f){f===g&&a()},delay_complete:function(){b=
!1;a()},mouse_move:function(){f=new d},pause:function(){f=new m}})}function d(){j();return new e({mouse_move:j,mouse_leave:function(){f=new i},delay_interrupted_timeout:function(){f.mouse_leave()},pause:function(){f=new m(!0)}})}function m(a){j();return new e({mouse_move:function(){a=!0;j()},mouse_leave:function(){a=!1},resume:function(){f=a?new d:v>0?new i:new o}})}function q(){p.notifyObservers("autorotating");x=(x-1+1)%A+1;p.notifyObservers("gotoCard",x);v--;return new e({rotation_complete:function(){f=
v>0?new i:new o},mouse_move:function(){f=v>0?new t:new o},pause:function(){f=new r}})}function t(){var a=!1;return new e({rotation_complete:function(){l();f=a?new m:new d},pause:function(){a=!0},resume:function(){a=!1}})}function r(){var a=!1;return new e({rotation_complete:function(){l();f=new m(a)},mouse_move:function(){a=!0},mouse_leave:function(){a=!1}})}function a(a){p.notifyObservers("userNavigation");x=h(a);p.notifyObservers("gotoCard",x);return new e({rotation_complete:function(){f=new o},
user_navigation:function(a){f=new u(a)},user_interaction:n})}function u(g){return new e({rotation_complete:function(){f=new a(g)},user_navigation:function(a){g=a},user_interaction:n})}function o(){p.notifyObservers("stopAutorotation");return new e({})}var b=b||{},p=new c,f=new function(){function a(){y[g]&&d&&(p.notifyObservers("ready"),f=new i,s&&f.pause(),b&&f.stop_autorotation())}var d=!1,b=!1,s=!1;return new e({fg_loaded:function(f){f===g&&a()},js_ready:function(){d=!0;a()},user_navigation:n,
stop_autorotation:function(){b=!0},pause:function(){s=!0},resume:function(){s=!1}})},s=b.fgIDs||[],A=s.length,g=s[0],x=b.card_num||1,y={},v=b.circular?Infinity:A;return{delayComplete:function(){f.delay_complete()},jsReady:function(){f.js_ready()},fgLoaded:function(a){y[a]=!0;g===a&&p.notifyObservers("atfLoaded");f.fg_loaded(a)},mouseMove:function(){f.mouse_move()},mouseLeave:function(){f.mouse_leave()},delayInterruptedTimeout:function(){f.delay_interrupted_timeout()},rotationComplete:function(){f.rotation_complete()},
gotoCard:function(a){f.goto_card(a)},userInteraction:function(){f.user_interaction()},userNavigation:function(a){f.user_navigation(a)},stopAutorotation:function(){f.stop_autorotation()},pause:function(){f.pause()},resume:function(){f.resume()},addObserver:p.addObserver,removeObserver:p.removeObserver}}});c.when("herotator-btf").register("herotator",function(c){return c});c.register("herotator-btf",function(){return function(k,n){function b(a){return function(){c.when("gw-desktop-herotator/controller").execute(function(){w[a]()})}}
function l(a,f,g){a.addEventListener?a.addEventListener(f,g,!1):a.attachEvent("on"+f,g)}function j(a,f){p[a]=[];var g=f.length;if(g>0)for(var d=0;d<g;d++)(function(g){var d=new Image;d.onload=function(){p[a].splice(t(p[a],d),1);p[a]&&p[a].length===0&&c.when("gw-desktop-herotator/controller").execute(function(){var f=document.getElementById("gw-ftGr-"+a),g=f.className,g=g.replace(/\s*\ba\-lazy\-loaded\b\s*/,"");f.className=g;w.fgLoaded(a)});c.when("A").execute(function(f){var g=f.$("#gw-ftGr-"+a+" img.a-dynamic-image");
f.loadDynamicImage(g)})};p[a].push(d);d.src=f[g].src})(d);else c.when("gw-desktop-herotator/controller").execute(function(){w.fgLoaded(a)})}function h(){o=Date.now()}function e(){A||m()}function i(){x=x?Math.min(x,Date.now()):Date.now();clearTimeout(a.timeout_id);clearTimeout(i.timeout_id);i.timeout_id=setTimeout(function(){i.timeout_id=0;w.delayInterruptedTimeout()},3E3)}function d(){A=!0}function m(){if(!m.sent)clearTimeout(m.timeout),m.timeout=setTimeout(function(){q(k.uri,k.data);m.sent=!0},2E3)}
function q(a,f){c.when("A").execute(function(g){g.$.ajax(a,{async:!1,cache:!1,type:"post",data:f})})}function t(a,f){if(a.indexOf)return a.indexOf(f);for(var g=0;g<a.length;g++)if(a[g]===f)return g}function r(){v("#gw-desktop-herotator").addClass("gw-desktop-herotator-ready");c.register("herotator-controls",function(){var a=v("#gw-desktop-herotator-controls"),f=a.find("a");f.length>1?(f.click(function(a){a.preventDefault();(a=v(this).attr("href").match(/^\#gw-ftGr-(\w+-hero-[\w\d\-]+)/))&&w.userNavigation(a[1])}),
f.each(function(){var a=v(v(this).attr("href")),f=a.find(".gw-ftGr-desktop-hero-alt").text();(f=f||a.find(".image-map.shogun-widget img").attr("alt"))&&v(this).find(".gw-text").text(f)}),a.find("li").fadeIn(800)):a.hide();return{controls:a,links:f}})}function a(){g<x&&(s-=x-g,x=0);g=Date.now();a.timeout_id=setTimeout(function(){s=f;w.delayComplete()},s)}function u(a,f){if(u.current_card!==f)u.current_card=f,y.gotoPage(f),v("#gw-desktop-herotator-controls li a").removeClass("active"),v("#gw-desktop-herotator-controls li a.herotator-goToPage-"+
f).addClass("active"),E.notifyObservers("page_changed");setTimeout(function(){w.rotationComplete()},250)}var o=Date.now(),p={},f=5E3,s=f,A=!1,g=0,x=0,y,v,z=document.getElementById("gw-desktop-herotator").getElementsByTagName("ol")[0],E,w;l(z,"click",b("userInteraction"));l(z,"mouseenter",b("mouseMove"));l(z,"mousemove",b("mouseMove"));l(z,"mouseleave",b("mouseLeave"));l(z,"touchstart",b("userInteraction"));l(z,"touchmove",b("userInteraction"));l(z,"touchend",b("userInteraction"));l(z,"touchcancel",
b("userInteraction"));for(var z=document.getElementById("gw-desktop-herotator").getElementsByTagName("li")[0],C=0,B=z.childNodes[C];B&&String(B.nodeName).toLowerCase()!=="div";)C++,B=z.childNodes[C];C=B;z=String(C.id).replace(/^gw-ftGr-/,"");C=C.getElementsByTagName("img");j(z,C||[]);for(var G=[z],z=0;n[z];)G.push(n[z].fgID),z++;c.when("gw-herotator-controller").execute(function(g){w=new g({fgIDs:G});w.addObserver("atfLoaded",h);w.addObserver("delayBegin",a);w.addObserver("delayInterrupted",i);w.addObserver("gotoCard",
u);w.addObserver("userNavigation",e);w.addObserver("stopAutorotation",d);w.addObserver("ready",function(){var a=Date.now()-o;s=Math.max(f-a,1);r();v("#gw-desktop-herotator").addClass("gw-desktop-herotator-ready")});c.register("gw-desktop-herotator/controller");c.when("generic-observable").register("gw-desktop-herotator",function(a){E=new a;return{getAutorotationDelay:function(){return f},setAutorotationDelay:function(a){a=parseInt(a,10);s=a-(f-s);f=a},stopAutorotation:function(){w.stopAutorotation()},
disableNavigation:function(){v("#gw-desktop-herotator-controls").hide();y.pause()},enableNavigation:function(){v("#gw-desktop-herotator-controls").show();y.resume()},pause:function(){w.pause()},resume:function(){w.resume()},addObserver:E.addObserver,removeObserver:E.removeObserver}})});c.when("A","a-carousel-framework","gwAjax").execute(function(a,f,g){function d(){for(var a=0;n[a];){var f=n[a].fgID,g=n[a].content,b=document.getElementById("gw-ftGr-"+f);v(b).html(g);g=b.getElementsByTagName("img");
j(f,g);a++}}v=a.$;f.onInit("gateway-desktop-layout.herotator",function(){var b=a.$("#gw-desktop-herotator > .a-carousel-container");y=f.getCarousel(b);y.onChange("pageNumber",function(){var a=y.getAttr("pageNumber");w.gotoCard(a);a-=2;n[a]&&n[a].callbackUrl&&(g(n[a].callbackUrl,{type:"POST",id:"desktop-herotator-btf-"+n[a].fgID}),delete n[a].callbackUrl)});d();c.when("gw-desktop-herotator").register("gw-desktop-herotator/dom-ready");c.when("gw-desktop-herotator/controller","gw-desktop-herotator").execute(function(){w.jsReady()})})})}})})})(function(){var c=
window.AmazonUIPageJS||window.P,k=c._namespace||c.attributeErrors;return k?k("AmazonGatewayHerotatorJS"):c}(),window);