window.Modernizr=function(t,e,i){function n(t){x.cssText=t}function r(t,e){return n(k.join(t+";")+(e||""))}function s(t,e){return typeof t===e}function o(t,e){return!!~(""+t).indexOf(e)
}function a(t,e){for(var n in t){var r=t[n];if(!o(r,"-")&&x[r]!==i)return"pfx"==e?r:!0}return!1}function l(t,e,n){for(var r in t){var o=e[t[r]];if(o!==i)return n===!1?t[r]:s(o,"function")?o.bind(n||e):o
}return!1}function h(t,e,i){var n=t.charAt(0).toUpperCase()+t.slice(1),r=(t+" "+P.join(n+" ")+n).split(" ");return s(e,"string")||s(e,"undefined")?a(r,e):(r=(t+" "+T.join(n+" ")+n).split(" "),l(r,e,i))
}function c(){f.input=function(i){for(var n=0,r=i.length;r>n;n++)A[i[n]]=!!(i[n]in b);return A.list&&(A.list=!(!e.createElement("datalist")||!t.HTMLDataListElement)),A
}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" ")),f.inputtypes=function(t){for(var n,r,s,o=0,a=t.length;a>o;o++)b.setAttribute("type",r=t[o]),n="text"!==b.type,n&&(b.value=w,b.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(r)&&b.style.WebkitAppearance!==i?(m.appendChild(b),s=e.defaultView,n=s.getComputedStyle&&"textfield"!==s.getComputedStyle(b,null).WebkitAppearance&&0!==b.offsetHeight,m.removeChild(b)):/^(search|tel)$/.test(r)||(n=/^(url|email)$/.test(r)?b.checkValidity&&b.checkValidity()===!1:b.value!=w)),E[t[o]]=!!n;
return E}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var u,d,p="2.6.2",f={},g=!0,m=e.documentElement,v="modernizr",y=e.createElement(v),x=y.style,b=e.createElement("input"),w=":)",k=({}.toString," -webkit- -moz- -o- -ms- ".split(" ")),C="Webkit Moz O ms",P=C.split(" "),T=C.toLowerCase().split(" "),S={},E={},A={},M=[],_=M.slice,L=function(t,i,n,r){var s,o,a,l,h=e.createElement("div"),c=e.body,u=c||e.createElement("body");
if(parseInt(n,10))for(;n--;)a=e.createElement("div"),a.id=r?r[n]:v+(n+1),h.appendChild(a);return s=["&#173;",'<style id="s',v,'">',t,"</style>"].join(""),h.id=v,(c?h:u).innerHTML+=s,u.appendChild(h),c||(u.style.background="",u.style.overflow="hidden",l=m.style.overflow,m.style.overflow="hidden",m.appendChild(u)),o=i(h,t),c?h.parentNode.removeChild(h):(u.parentNode.removeChild(u),m.style.overflow=l),!!o
},D=function(){function t(t,r){r=r||e.createElement(n[t]||"div"),t="on"+t;var o=t in r;return o||(r.setAttribute||(r=e.createElement("div")),r.setAttribute&&r.removeAttribute&&(r.setAttribute(t,""),o=s(r[t],"function"),s(r[t],"undefined")||(r[t]=i),r.removeAttribute(t))),r=null,o
}var n={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return t}(),B={}.hasOwnProperty;d=s(B,"undefined")||s(B.call,"undefined")?function(t,e){return e in t&&s(t.constructor.prototype[e],"undefined")
}:function(t,e){return B.call(t,e)},Function.prototype.bind||(Function.prototype.bind=function(t){var e=this;if("function"!=typeof e)throw new TypeError;var i=_.call(arguments,1),n=function(){if(this instanceof n){var r=function(){};
r.prototype=e.prototype;var s=new r,o=e.apply(s,i.concat(_.call(arguments)));return Object(o)===o?o:s}return e.apply(t,i.concat(_.call(arguments)))};return n}),S.flexbox=function(){return h("flexWrap")
},S.hashchange=function(){return D("hashchange",t)&&(e.documentMode===i||e.documentMode>7)},S.history=function(){return!(!t.history||!history.pushState)},S.draganddrop=function(){var t=e.createElement("div");
return"draggable"in t||"ondragstart"in t&&"ondrop"in t},S.rgba=function(){return n("background-color:rgba(150,255,150,.5)"),o(x.backgroundColor,"rgba")},S.hsla=function(){return n("background-color:hsla(120,40%,100%,.5)"),o(x.backgroundColor,"rgba")||o(x.backgroundColor,"hsla")
},S.multiplebgs=function(){return n("background:url(https://),url(https://),red url(https://)"),/(url\s*\(.*?){3}/.test(x.background)},S.backgroundsize=function(){return h("backgroundSize")
},S.borderimage=function(){return h("borderImage")},S.borderradius=function(){return h("borderRadius")},S.boxshadow=function(){return h("boxShadow")},S.textshadow=function(){return""===e.createElement("div").style.textShadow
},S.opacity=function(){return r("opacity:.55"),/^0.55$/.test(x.opacity)},S.cssanimations=function(){return h("animationName")},S.csscolumns=function(){return h("columnCount")
},S.cssgradients=function(){var t="background-image:",e="gradient(linear,left top,right bottom,from(#9f9),to(white));",i="linear-gradient(left top,#9f9, white);";
return n((t+"-webkit- ".split(" ").join(e+t)+k.join(i+t)).slice(0,-t.length)),o(x.backgroundImage,"gradient")},S.cssreflections=function(){return h("boxReflect")
},S.csstransforms=function(){return!!h("transform")},S.csstransitions=function(){return h("transition")},S.fontface=function(){var t;return L('@font-face {font-family:"font";src:url("https://")}',function(i,n){var r=e.getElementById("smodernizr"),s=r.sheet||r.styleSheet,o=s?s.cssRules&&s.cssRules[0]?s.cssRules[0].cssText:s.cssText||"":"";
t=/src/i.test(o)&&0===o.indexOf(n.split(" ")[0])}),t},S.generatedcontent=function(){var t;return L(["#",v,"{font:0/0 a}#",v,':after{content:"',w,'";visibility:hidden;font:3px/1 a}'].join(""),function(e){t=e.offsetHeight>=3
}),t},S.localstorage=function(){try{return localStorage.setItem(v,v),localStorage.removeItem(v),!0}catch(t){return!1}},S.applicationcache=function(){return!!t.applicationCache
};for(var F in S)d(S,F)&&(u=F.toLowerCase(),f[u]=S[F](),M.push((f[u]?"":"no-")+u));return f.input||c(),f.addTest=function(t,e){if("object"==typeof t)for(var n in t)d(t,n)&&f.addTest(n,t[n]);
else{if(t=t.toLowerCase(),f[t]!==i)return f;e="function"==typeof e?e():e,"undefined"!=typeof g&&g&&(m.className+=" "+(e?"":"no-")+t),f[t]=e}return f},n(""),y=b=null,function(t,e){function i(t,e){var i=t.createElement("p"),n=t.getElementsByTagName("head")[0]||t.documentElement;
return i.innerHTML="x<style>"+e+"</style>",n.insertBefore(i.lastChild,n.firstChild)}function n(){var t=v.elements;return"string"==typeof t?t.split(" "):t}function r(t){var e=m[t[f]];
return e||(e={},g++,t[f]=g,m[g]=e),e}function s(t,i,n){if(i||(i=e),c)return i.createElement(t);n||(n=r(i));var s;return s=n.cache[t]?n.cache[t].cloneNode():p.test(t)?(n.cache[t]=n.createElem(t)).cloneNode():n.createElem(t),s.canHaveChildren&&!d.test(t)?n.frag.appendChild(s):s
}function o(t,i){if(t||(t=e),c)return t.createDocumentFragment();i=i||r(t);for(var s=i.frag.cloneNode(),o=0,a=n(),l=a.length;l>o;o++)s.createElement(a[o]);return s
}function a(t,e){e.cache||(e.cache={},e.createElem=t.createElement,e.createFrag=t.createDocumentFragment,e.frag=e.createFrag()),t.createElement=function(i){return v.shivMethods?s(i,t,e):e.createElem(i)
},t.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+n().join().replace(/\w+/g,function(t){return e.createElem(t),e.frag.createElement(t),'c("'+t+'")'
})+");return n}")(v,e.frag)}function l(t){t||(t=e);var n=r(t);return!v.shivCSS||h||n.hasCSS||(n.hasCSS=!!i(t,"article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}mark{background:#FF0;color:#000}")),c||a(t,n),t
}var h,c,u=t.html5||{},d=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,p=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,f="_html5shiv",g=0,m={};
!function(){try{var t=e.createElement("a");t.innerHTML="<xyz></xyz>",h="hidden"in t,c=1==t.childNodes.length||function(){e.createElement("a");var t=e.createDocumentFragment();
return"undefined"==typeof t.cloneNode||"undefined"==typeof t.createDocumentFragment||"undefined"==typeof t.createElement}()}catch(i){h=!0,c=!0}}();var v={elements:u.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",shivCSS:u.shivCSS!==!1,supportsUnknownElements:c,shivMethods:u.shivMethods!==!1,type:"default",shivDocument:l,createElement:s,createDocumentFragment:o};
t.html5=v,l(e)}(this,e),f._version=p,f._prefixes=k,f._domPrefixes=T,f._cssomPrefixes=P,f.hasEvent=D,f.testProp=function(t){return a([t])},f.testAllProps=h,f.testStyles=L,f.prefixed=function(t,e,i){return e?h(t,e,i):h(t,"pfx")
},m.className=m.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(g?" js "+M.join(" "):""),f}(this,this.document),function(t,e,i){function n(t){return"[object Function]"==m.call(t)
}function r(t){return"string"==typeof t}function s(){}function o(t){return!t||"loaded"==t||"complete"==t||"uninitialized"==t}function a(){var t=v.shift();y=1,t?t.t?f(function(){("c"==t.t?d.injectCss:d.injectJs)(t.s,0,t.a,t.x,t.e,1)
},0):(t(),a()):y=0}function l(t,i,n,r,s,l,h){function c(e){if(!p&&o(u.readyState)&&(x.r=p=1,!y&&a(),u.onload=u.onreadystatechange=null,e)){"img"!=t&&f(function(){w.removeChild(u)
},50);for(var n in S[i])S[i].hasOwnProperty(n)&&S[i][n].onload()}}var h=h||d.errorTimeout,u=e.createElement(t),p=0,m=0,x={t:n,s:i,e:s,a:l,x:h};1===S[i]&&(m=1,S[i]=[]),"object"==t?u.data=i:(u.src=i,u.type=t),u.width=u.height="0",u.onerror=u.onload=u.onreadystatechange=function(){c.call(this,m)
},v.splice(r,0,x),"img"!=t&&(m||2===S[i]?(w.insertBefore(u,b?null:g),f(c,h)):S[i].push(u))}function h(t,e,i,n,s){return y=0,e=e||"j",r(t)?l("c"==e?C:k,t,e,this.i++,i,n,s):(v.splice(this.i++,0,t),1==v.length&&a()),this
}function c(){var t=d;return t.loader={load:h,i:0},t}var u,d,p=e.documentElement,f=t.setTimeout,g=e.getElementsByTagName("script")[0],m={}.toString,v=[],y=0,x="MozAppearance"in p.style,b=x&&!!e.createRange().compareNode,w=b?p:g.parentNode,p=t.opera&&"[object Opera]"==m.call(t.opera),p=!!e.attachEvent&&!p,k=x?"object":p?"script":"img",C=p?"script":k,P=Array.isArray||function(t){return"[object Array]"==m.call(t)
},T=[],S={},E={timeout:function(t,e){return e.length&&(t.timeout=e[0]),t}};d=function(t){function e(t){var e,i,n,t=t.split("!"),r=T.length,s=t.pop(),o=t.length,s={url:s,origUrl:s,prefixes:t};
for(i=0;o>i;i++)n=t[i].split("="),(e=E[n.shift()])&&(s=e(s,n));for(i=0;r>i;i++)s=T[i](s);return s}function o(t,r,s,o,a){var l=e(t),h=l.autoCallback;l.url.split(".").pop().split("?").shift(),l.bypass||(r&&(r=n(r)?r:r[t]||r[o]||r[t.split("/").pop().split("?")[0]]),l.instead?l.instead(t,r,s,o,a):(S[l.url]?l.noexec=!0:S[l.url]=1,s.load(l.url,l.forceCSS||!l.forceJS&&"css"==l.url.split(".").pop().split("?").shift()?"c":i,l.noexec,l.attrs,l.timeout),(n(r)||n(h))&&s.load(function(){c(),r&&r(l.origUrl,a,o),h&&h(l.origUrl,a,o),S[l.url]=2
})))}function a(t,e){function i(t,i){if(t){if(r(t))i||(u=function(){var t=[].slice.call(arguments);d.apply(this,t),p()}),o(t,u,e,0,h);else if(Object(t)===t)for(l in a=function(){var e,i=0;
for(e in t)t.hasOwnProperty(e)&&i++;return i}(),t)t.hasOwnProperty(l)&&(!i&&!--a&&(n(u)?u=function(){var t=[].slice.call(arguments);d.apply(this,t),p()}:u[l]=function(t){return function(){var e=[].slice.call(arguments);
t&&t.apply(this,e),p()}}(d[l])),o(t[l],u,e,l,h))}else!i&&p()}var a,l,h=!!t.test,c=t.load||t.both,u=t.callback||s,d=u,p=t.complete||s;i(h?t.yep:t.nope,!!c),c&&i(c)
}var l,h,u=this.yepnope.loader;if(r(t))o(t,0,u,0);else if(P(t))for(l=0;l<t.length;l++)h=t[l],r(h)?o(h,0,u,0):P(h)?d(h):Object(h)===h&&a(h,u);else Object(t)===t&&a(t,u)
},d.addPrefix=function(t,e){E[t]=e},d.addFilter=function(t){T.push(t)},d.errorTimeout=1e4,null==e.readyState&&e.addEventListener&&(e.readyState="loading",e.addEventListener("DOMContentLoaded",u=function(){e.removeEventListener("DOMContentLoaded",u,0),e.readyState="complete"
},0)),t.yepnope=c(),t.yepnope.executeStack=a,t.yepnope.injectJs=function(t,i,n,r,l,h){var c,u,p=e.createElement("script"),r=r||d.errorTimeout;p.src=t;for(u in n)p.setAttribute(u,n[u]);
i=h?a:i||s,p.onreadystatechange=p.onload=function(){!c&&o(p.readyState)&&(c=1,i(),p.onload=p.onreadystatechange=null)},f(function(){c||(c=1,i(1))},r),l?p.onload():g.parentNode.insertBefore(p,g)
},t.yepnope.injectCss=function(t,i,n,r,o,l){var h,r=e.createElement("link"),i=l?a:i||s;r.href=t,r.rel="stylesheet",r.type="text/css";for(h in n)r.setAttribute(h,n[h]);
o||(g.parentNode.insertBefore(r,g),f(i,0))}}(this,document),Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};