var requirejs,require,define;!function(global){function isFunction(t){return"[object Function]"===ostring.call(t)}function isArray(t){return"[object Array]"===ostring.call(t)
}function each(t,e){if(t){var i;for(i=0;i<t.length&&(!t[i]||!e(t[i],i,t));i+=1);}}function eachReverse(t,e){if(t){var i;for(i=t.length-1;i>-1&&(!t[i]||!e(t[i],i,t));i-=1);}}function hasProp(t,e){return hasOwn.call(t,e)
}function eachProp(t,e){var i;for(i in t)if(t.hasOwnProperty(i)&&e(t[i],i))break}function mixin(t,e,i,n){return e&&eachProp(e,function(e,r){(i||!hasProp(t,r))&&(n&&"string"!=typeof e?(t[r]||(t[r]={}),mixin(t[r],e,i,n)):t[r]=e)
}),t}function bind(t,e){return function(){return e.apply(t,arguments)}}function scripts(){return document.getElementsByTagName("script")}function getGlobal(t){if(!t)return t;
var e=global;return each(t.split("."),function(t){e=e[t]}),e}function makeContextModuleFunc(t,e,i){return function(){var n,r=aps.call(arguments,0);return i&&isFunction(n=r[r.length-1])&&(n.__requireJsBuild=!0),r.push(e),t.apply(null,r)
}}function addRequireMethods(t,e,i){each([["toUrl"],["undef"],["defined","requireDefined"],["specified","requireSpecified"]],function(n){var r=n[1]||n[0];t[n[0]]=e?makeContextModuleFunc(e[r],i):function(){var t=contexts[defContextName];
return t[r].apply(t,arguments)}})}function makeError(t,e,i,n){var r=new Error(e+"\nhttps://requirejs.org/docs/errors.html#"+t);return r.requireType=t,r.requireModules=n,i&&(r.originalError=i),r
}function newContext(t){function e(t){var e,i;for(e=0;t[e];e+=1)if(i=t[e],"."===i)t.splice(e,1),e-=1;else if(".."===i){if(1===e&&(".."===t[2]||".."===t[0]))break;
e>0&&(t.splice(e-1,2),e-=2)}}function i(t,i,n){var r,s,o,a,l,h,c,u,d,p,f,g=i&&i.split("/"),m=g,v=T.map,y=v&&v["*"];if(t&&"."===t.charAt(0)&&(i?(m=T.pkgs[i]?g=[i]:g.slice(0,g.length-1),t=m.concat(t.split("/")),e(t),s=T.pkgs[r=t[0]],t=t.join("/"),s&&t===r+"/"+s.main&&(t=r)):0===t.indexOf("./")&&(t=t.substring(2))),n&&(g||y)&&v){for(a=t.split("/"),l=a.length;l>0;l-=1){if(c=a.slice(0,l).join("/"),g)for(h=g.length;h>0;h-=1)if(o=v[g.slice(0,h).join("/")],o&&(o=o[c])){u=o,d=l;
break}if(u)break;!p&&y&&y[c]&&(p=y[c],f=l)}!u&&p&&(u=p,d=f),u&&(a.splice(0,d,u),t=a.join("/"))}return t}function n(t){isBrowser&&each(scripts(),function(e){return e.getAttribute("data-requiremodule")===t&&e.getAttribute("data-requirecontext")===w.contextName?(e.parentNode.removeChild(e),!0):void 0
})}function r(t){var e=T.paths[t];return e&&isArray(e)&&e.length>1?(n(t),e.shift(),w.undef(t),w.require([t]),!0):void 0}function s(t,e,n,r){var s,o,a,l=t?t.indexOf("!"):-1,h=null,c=e?e.name:null,u=t,d=!0,p="";
return t||(d=!1,t="_@r"+(_+=1)),-1!==l&&(h=t.substring(0,l),t=t.substring(l+1,t.length)),h&&(h=i(h,c,r),o=M[h]),t&&(h?p=o&&o.normalize?o.normalize(t,function(t){return i(t,c,r)
}):i(t,c,r):(p=i(t,c,r),s=w.nameToUrl(p))),a=!h||o||n?"":"_unnormalized"+(D+=1),{prefix:h,name:p,parentMap:e,unnormalized:!!a,url:s,originalName:u,isDefine:d,id:(h?h+"!"+p:p)+a}
}function o(t){var e=t.id,i=S[e];return i||(i=S[e]=new w.Module(t)),i}function a(t,e,i){var n=t.id,r=S[n];!hasProp(M,n)||r&&!r.defineEmitComplete?o(t).on(e,i):"defined"===e&&i(M[n])
}function l(t,e){var i=t.requireModules,n=!1;e?e(t):(each(i,function(e){var i=S[e];i&&(i.error=t,i.events.error&&(n=!0,i.emit("error",t)))}),n||req.onError(t))}function h(){globalDefQueue.length&&(apsp.apply(E,[E.length-1,0].concat(globalDefQueue)),globalDefQueue=[])
}function c(t,e,i){var n=t&&t.map,r=makeContextModuleFunc(i||w.require,n,e);return addRequireMethods(r,w,n),r.isBrowser=isBrowser,r}function u(t){delete S[t],each(L,function(e,i){return e.map.id===t?(L.splice(i,1),e.defined||(w.waitCount-=1),!0):void 0
})}function d(t,e,i){var n,r=t.map.id,s=t.depMaps;if(t.inited)return e[r]?t:(e[r]=!0,each(s,function(t){var r=t.id,s=S[r];if(s&&!i[r]&&s.inited&&s.enabled)return n=d(s,e,i)
}),i[r]=!0,n)}function p(t,e,i){var n=t.map.id,r=t.depMaps;if(t.inited&&t.map.isDefine)return e[n]?M[n]:(e[n]=t,each(r,function(r){var s,o=r.id,a=S[o];if(!k[o]&&a){if(!a.inited||!a.enabled)return i[n]=!0,void 0;
s=p(a,e,i),i[o]||t.defineDepById(o,s)}}),t.check(!0),M[n])}function f(t){t.check()}function g(){var t,e,i,s,o=1e3*T.waitSeconds,a=o&&w.startTime+o<(new Date).getTime(),h=[],c=!1,u=!0;
if(!b){if(b=!0,eachProp(S,function(i){if(t=i.map,e=t.id,i.enabled&&!i.error)if(!i.inited&&a)r(e)?(s=!0,c=!0):(h.push(e),n(e));else if(!i.inited&&i.fetched&&t.isDefine&&(c=!0,!t.prefix))return u=!1
}),a&&h.length)return i=makeError("timeout","Load timeout for modules: "+h,null,h),i.contextName=w.contextName,l(i);u&&(each(L,function(t){if(!t.defined){var e=d(t,{},{}),i={};
e&&(p(e,i,{}),eachProp(i,f))}}),eachProp(S,f)),a&&!s||!c||!isBrowser&&!isWebWorker||C||(C=setTimeout(function(){C=0,g()},50)),b=!1}}function m(t){o(s(t[0],null,!0)).init(t[1],t[2])
}function v(t,e,i,n){t.detachEvent&&!isOpera?n&&t.detachEvent(n,e):t.removeEventListener(i,e,!1)}function y(t){var e=t.currentTarget||t.srcElement;return v(e,w.onScriptLoad,"load","onreadystatechange"),v(e,w.onScriptError,"error"),{node:e,id:e&&e.getAttribute("data-requiremodule")}
}var b,x,w,k,C,T={waitSeconds:7,baseUrl:"./",paths:{},pkgs:{},shim:{}},S={},P={},E=[],M={},A={},_=1,D=1,L=[];return k={require:function(t){return c(t)},exports:function(t){return t.usingExports=!0,t.map.isDefine?t.exports=M[t.map.id]={}:void 0
},module:function(t){return t.module={id:t.map.id,uri:t.map.url,config:function(){return T.config&&T.config[t.map.id]||{}},exports:M[t.map.id]}}},x=function(t){this.events=P[t.id]||{},this.map=t,this.shim=T.shim[t.id],this.depExports=[],this.depMaps=[],this.depMatched=[],this.pluginMaps={},this.depCount=0
},x.prototype={init:function(t,e,i,n){n=n||{},this.inited||(this.factory=e,i?this.on("error",i):this.events.error&&(i=bind(this,function(t){this.emit("error",t)})),this.depMaps=t&&t.slice(0),this.depMaps.rjsSkipMap=t.rjsSkipMap,this.errback=i,this.inited=!0,this.ignore=n.ignore,n.enabled||this.enabled?this.enable():this.check())
},defineDepById:function(t,e){var i;return each(this.depMaps,function(e,n){return e.id===t?(i=n,!0):void 0}),this.defineDep(i,e)},defineDep:function(t,e){this.depMatched[t]||(this.depMatched[t]=!0,this.depCount-=1,this.depExports[t]=e)
},fetch:function(){if(!this.fetched){this.fetched=!0,w.startTime=(new Date).getTime();var t=this.map;return this.shim?(c(this,!0)(this.shim.deps||[],bind(this,function(){return t.prefix?this.callPlugin():this.load()
})),void 0):t.prefix?this.callPlugin():this.load()}},load:function(){var t=this.map.url;A[t]||(A[t]=!0,w.load(this.map.id,t))},check:function(t){if(this.enabled&&!this.enabling){var e,i,n=this.map.id,r=this.depExports,s=this.exports,o=this.factory;
if(this.inited){if(this.error)this.emit("error",this.error);else if(!this.defining){if(this.defining=!0,this.depCount<1&&!this.defined){if(isFunction(o)){if(this.events.error)try{s=w.execCb(n,o,r,s)
}catch(a){e=a}else s=w.execCb(n,o,r,s);if(this.map.isDefine&&(i=this.module,i&&void 0!==i.exports&&i.exports!==this.exports?s=i.exports:void 0===s&&this.usingExports&&(s=this.exports)),e)return e.requireMap=this.map,e.requireModules=[this.map.id],e.requireType="define",l(this.error=e)
}else s=o;this.exports=s,this.map.isDefine&&!this.ignore&&(M[n]=s,req.onResourceLoad&&req.onResourceLoad(w,this.map,this.depMaps)),delete S[n],this.defined=!0,w.waitCount-=1,0===w.waitCount&&(L=[])
}this.defining=!1,t||this.defined&&!this.defineEmitted&&(this.defineEmitted=!0,this.emit("defined",this.exports),this.defineEmitComplete=!0)}}else this.fetch()}},callPlugin:function(){var t=this.map,e=t.id,n=s(t.prefix,null,!1,!0);
a(n,"defined",bind(this,function(n){var r,h,d,p=this.map.name,f=this.map.parentMap?this.map.parentMap.name:null;return this.map.unnormalized?(n.normalize&&(p=n.normalize(p,function(t){return i(t,f,!0)
})||""),h=s(t.prefix+"!"+p,this.map.parentMap,!1,!0),a(h,"defined",bind(this,function(t){this.init([],function(){return t},null,{enabled:!0,ignore:!0})})),d=S[h.id],d&&(this.events.error&&d.on("error",bind(this,function(t){this.emit("error",t)
})),d.enable()),void 0):(r=bind(this,function(t){this.init([],function(){return t},null,{enabled:!0})}),r.error=bind(this,function(t){this.inited=!0,this.error=t,t.requireModules=[e],eachProp(S,function(t){0===t.map.id.indexOf(e+"_unnormalized")&&u(t.map.id)
}),l(t)}),r.fromText=function(t,e){var i=useInteractive;i&&(useInteractive=!1),o(s(t)),req.exec(e),i&&(useInteractive=!0),w.completeLoad(t)},n.load(t.name,c(t.parentMap,!0,function(t,e,i){return t.rjsSkipMap=!0,w.require(t,e,i)
}),r,T),void 0)})),w.enable(n,this),this.pluginMaps[n.id]=n},enable:function(){this.enabled=!0,this.waitPushed||(L.push(this),w.waitCount+=1,this.waitPushed=!0),this.enabling=!0,each(this.depMaps,bind(this,function(t,e){var i,n,r;
if("string"==typeof t){if(t=s(t,this.map.isDefine?this.map:this.map.parentMap,!1,!this.depMaps.rjsSkipMap),this.depMaps[e]=t,r=k[t.id])return this.depExports[e]=r(this),void 0;
this.depCount+=1,a(t,"defined",bind(this,function(t){this.defineDep(e,t),this.check()})),this.errback&&a(t,"error",this.errback)}i=t.id,n=S[i],k[i]||!n||n.enabled||w.enable(t,this)
})),eachProp(this.pluginMaps,bind(this,function(t){var e=S[t.id];e&&!e.enabled&&w.enable(t,this)})),this.enabling=!1,this.check()},on:function(t,e){var i=this.events[t];
i||(i=this.events[t]=[]),i.push(e)},emit:function(t,e){each(this.events[t],function(t){t(e)}),"error"===t&&delete this.events[t]}},w={config:T,contextName:t,registry:S,defined:M,urlFetched:A,waitCount:0,defQueue:E,Module:x,makeModuleMap:s,configure:function(t){t.baseUrl&&"/"!==t.baseUrl.charAt(t.baseUrl.length-1)&&(t.baseUrl+="/");
var e=T.pkgs,i=T.shim,n=T.paths,r=T.map;mixin(T,t,!0),T.paths=mixin(n,t.paths,!0),t.map&&(T.map=mixin(r||{},t.map,!0,!0)),t.shim&&(eachProp(t.shim,function(t,e){isArray(t)&&(t={deps:t}),t.exports&&!t.exports.__buildReady&&(t.exports=w.makeShimExports(t.exports)),i[e]=t
}),T.shim=i),t.packages&&(each(t.packages,function(t){var i;t="string"==typeof t?{name:t}:t,i=t.location,e[t.name]={name:t.name,location:i||t.name,main:(t.main||"main").replace(currDirRegExp,"").replace(jsSuffixRegExp,"")}
}),T.pkgs=e),eachProp(S,function(t,e){t.inited||t.map.unnormalized||(t.map=s(e))}),(t.deps||t.callback)&&w.require(t.deps||[],t.callback)},makeShimExports:function(t){var e;
return"string"==typeof t?(e=function(){return getGlobal(t)},e.exports=t,e):function(){return t.apply(global,arguments)}},requireDefined:function(t,e){return hasProp(M,s(t,e,!1,!0).id)
},requireSpecified:function(t,e){return t=s(t,e,!1,!0).id,hasProp(M,t)||hasProp(S,t)},require:function(e,i,n,r){var a,c,u,d,p;if("string"==typeof e)return isFunction(i)?l(makeError("requireargs","Invalid require call"),n):req.get?req.get(w,e,i):(a=e,r=i,u=s(a,r,!1,!0),c=u.id,hasProp(M,c)?M[c]:l(makeError("notloaded",'Module name "'+c+'" has not been loaded yet for context: '+t)));
for(n&&!isFunction(n)&&(r=n,n=void 0),i&&!isFunction(i)&&(r=i,i=void 0),h();E.length;){if(p=E.shift(),null===p[0])return l(makeError("mismatch","Mismatched anonymous define() module: "+p[p.length-1]));
m(p)}return d=o(s(null,r)),d.init(e,i,n,{enabled:!0}),g(),w.require},undef:function(t){h();var e=s(t,null,!0),i=S[t];delete M[t],delete A[e.url],delete P[t],i&&(i.events.defined&&(P[t]=i.events),u(t))
},enable:function(t){var e=S[t.id];e&&o(t).enable()},completeLoad:function(t){var e,i,n,s=T.shim[t]||{},o=s.exports&&s.exports.exports;for(h();E.length;){if(i=E.shift(),null===i[0]){if(i[0]=t,e)break;
e=!0}else i[0]===t&&(e=!0);m(i)}if(n=S[t],!e&&!M[t]&&n&&!n.inited){if(!(!T.enforceDefine||o&&getGlobal(o)))return r(t)?void 0:l(makeError("nodefine","No define call for "+t,null,[t]));
m([t,s.deps||[],s.exports])}g()},toUrl:function(t,e){var n=t.lastIndexOf("."),r=null;return-1!==n&&(r=t.substring(n,t.length),t=t.substring(0,n)),w.nameToUrl(i(t,e&&e.id,!0),r)
},nameToUrl:function(t,e){var i,n,r,s,o,a,l,h,c;if(req.jsExtRegExp.test(t))h=t+(e||"");else{for(i=T.paths,n=T.pkgs,o=t.split("/"),a=o.length;a>0;a-=1){if(l=o.slice(0,a).join("/"),r=n[l],c=i[l]){isArray(c)&&(c=c[0]),o.splice(0,a,c);
break}if(r){s=t===r.name?r.location+"/"+r.main:r.location,o.splice(0,a,s);break}}h=o.join("/"),h+=e||(/\?/.test(h)?"":".js"),h=("/"===h.charAt(0)||h.match(/^[\w\+\.\-]+:/)?"":T.baseUrl)+h
}return T.urlArgs?h+((-1===h.indexOf("?")?"?":"&")+T.urlArgs):h},load:function(t,e){req.load(w,t,e)},execCb:function(t,e,i,n){return e.apply(n,i)},onScriptLoad:function(t){if("load"===t.type||readyRegExp.test((t.currentTarget||t.srcElement).readyState)){interactiveScript=null;
var e=y(t);w.completeLoad(e.id)}},onScriptError:function(t){var e=y(t);return r(e.id)?void 0:l(makeError("scripterror","Script error",t,[e.id]))}}}function getInteractiveScript(){return interactiveScript&&"interactive"===interactiveScript.readyState?interactiveScript:(eachReverse(scripts(),function(t){return"interactive"===t.readyState?interactiveScript=t:void 0
}),interactiveScript)}var req,s,head,baseElement,dataMain,src,interactiveScript,currentlyAddingScript,mainScript,subPath,version="2.0.6",commentRegExp=/(\/\*([\s\S]*?)\*\/|([^:]|^)\/\/(.*)$)/gm,cjsRequireRegExp=/[^.]\s*require\s*\(\s*["']([^'"\s]+)["']\s*\)/g,jsSuffixRegExp=/\.js$/,currDirRegExp=/^\.\//,op=Object.prototype,ostring=op.toString,hasOwn=op.hasOwnProperty,ap=Array.prototype,aps=ap.slice,apsp=ap.splice,isBrowser=!("undefined"==typeof window||!navigator||!document),isWebWorker=!isBrowser&&"undefined"!=typeof importScripts,readyRegExp=isBrowser&&"PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/,defContextName="_",isOpera="undefined"!=typeof opera&&"[object Opera]"===opera.toString(),contexts={},cfg={},globalDefQueue=[],useInteractive=!1;
if("undefined"==typeof define){if("undefined"!=typeof requirejs){if(isFunction(requirejs))return;cfg=requirejs,requirejs=void 0}"undefined"==typeof require||isFunction(require)||(cfg=require,require=void 0),req=requirejs=function(t,e,i,n){var r,s,o=defContextName;
return isArray(t)||"string"==typeof t||(s=t,isArray(e)?(t=e,e=i,i=n):t=[]),s&&s.context&&(o=s.context),r=contexts[o],r||(r=contexts[o]=req.s.newContext(o)),s&&r.configure(s),r.require(t,e,i)
},req.config=function(t){return req(t)},require||(require=req),req.version=version,req.jsExtRegExp=/^\/|:|\?|\.js$/,req.isBrowser=isBrowser,s=req.s={contexts:contexts,newContext:newContext},req({}),addRequireMethods(req),isBrowser&&(head=s.head=document.getElementsByTagName("head")[0],baseElement=document.getElementsByTagName("base")[0],baseElement&&(head=s.head=baseElement.parentNode)),req.onError=function(t){throw t
},req.load=function(t,e,i){var n,r=t&&t.config||{};return isBrowser?(n=r.xhtml?document.createElementNS("https://www.w3.org/1999/xhtml","html:script"):document.createElement("script"),n.type=r.scriptType||"text/javascript",n.charset="utf-8",n.async=!0,n.setAttribute("data-requirecontext",t.contextName),n.setAttribute("data-requiremodule",e),!n.attachEvent||n.attachEvent.toString&&n.attachEvent.toString().indexOf("[native code")<0||isOpera?(n.addEventListener("load",t.onScriptLoad,!1),n.addEventListener("error",t.onScriptError,!1)):(useInteractive=!0,n.attachEvent("onreadystatechange",t.onScriptLoad)),n.src=i,currentlyAddingScript=n,baseElement?head.insertBefore(n,baseElement):head.appendChild(n),currentlyAddingScript=null,n):(isWebWorker&&(importScripts(i),t.completeLoad(e)),void 0)
},isBrowser&&eachReverse(scripts(),function(t){return head||(head=t.parentNode),dataMain=t.getAttribute("data-main"),dataMain?(cfg.baseUrl||(src=dataMain.split("/"),mainScript=src.pop(),subPath=src.length?src.join("/")+"/":"./",cfg.baseUrl=subPath,dataMain=mainScript),dataMain=dataMain.replace(jsSuffixRegExp,""),cfg.deps=cfg.deps?cfg.deps.concat(dataMain):[dataMain],!0):void 0
}),define=function(t,e,i){var n,r;"string"!=typeof t&&(i=e,e=t,t=null),isArray(e)||(i=e,e=[]),!e.length&&isFunction(i)&&i.length&&(i.toString().replace(commentRegExp,"").replace(cjsRequireRegExp,function(t,i){e.push(i)
}),e=(1===i.length?["require"]:["require","exports","module"]).concat(e)),useInteractive&&(n=currentlyAddingScript||getInteractiveScript(),n&&(t||(t=n.getAttribute("data-requiremodule")),r=contexts[n.getAttribute("data-requirecontext")])),(r?r.defQueue:globalDefQueue).push([t,e,i])
},define.amd={jQuery:!0},req.exec=function(text){return eval(text)},req(cfg)}}(this);