//tealium universal tag - utag.3 ut4.0.201502271042, Copyright 2015 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[];window.webo_parseProfile=function(returned_data){var dat=new Date(),local_cooker;if(window.TEALIUM&&window.TEALIUM.CookieHandler){local_cooker=new window.TEALIUM.CookieHandler();}
dat=dat.getFullYear()+"-"+("0"+(dat.getMonth()+1)).slice(-2)+"-"+("0"+dat.getDate()).slice(-2)+"-"+("0"+dat.getHours()).slice(-2)+"-"+("0"+dat.getMinutes()).slice(-2);if(!returned_data){return false;}
window.utag.data=window.utag.data||{};utag.data.webo_response=returned_data;utag.data.webo_response.weboQueryDate=dat;utag.data.webo_response.weboCalls=1;utag.data.webo_response.oasCalls=1;utag.data.webo_response.social_demo=utag.data.webo_response.socio_demographics;try{delete utag.data.webo_response.socio_demographics;}catch(e){utag.data.webo_response.socio_demographics=undefined;}
utag.data.webo_response.clusters=(utag.data.webo_response.clusters.join&&utag.data.webo_response.clusters.length>0)?("S="+utag.data.webo_response.clusters.join("&S=")):"";utag.data.webo_response.audiences=(utag.data.webo_response.audiences.join&&utag.data.webo_response.audiences.length>0)?("aud="+utag.data.webo_response.audiences.join("&aud=")):"";utag.data.webo_response.social_demo="social_class="+utag.data.webo_response.social_demo.social_class+"&age="+utag.data.webo_response.social_demo.age+"&gender="+utag.data.webo_response.social_demo.gender;local_cooker.subcookie.set("webo_tealium",utag.data.webo_response,45);return true;};u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={"base_url":"//aimfar.solution.weborama.fr/fcgi-bin/dispatch.fcgi?d.A=prd&d.format=jsonp&d.key=h4f6j7se3h0g&d.callback=webo_parseProfile"
};if(document.readyState&&document.readyState!=="complete"){document.write("<scr"+"ipt type='text/javascript' src='"+u.data.base_url+"' id='teal_weborama'></scr"+"ipt>");}
for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("3","schibsted.leboncoin");}catch(error){utag.DB(error);}
